### ISSUE TITLE
Hnot ard returns ormatting in browser 

### ISSUE THREAD

**Issue by ar0berts** [bbucior/drposter#1]

**Comment by ar0berts** [comment]
The package produces beautiful output in the RStudio browser however once it is viewed in a web browser the hard break after the title is lost.

Browsers tried: Chrome Version 62.0.3202.94 (Official Build) (32-bit); Internet Explorer 11.09 and Opera
OS Tried: Ununtu 32 bit LTS 16.04 and Windows 7 Enterprise Sp 1
Fixes tried
```
## A Title__         <- two spaces and a new line
## A Title\           <- a backslash and a new line
## A Title  \           <- a backslash, 2 spaces and a new line
variant: escaped_line_breaks in the YAML header
```
Attached are the .Rmd and the screenshots of the appearance in RStudio and a browser.

I do hope there is a fix for this as your package makes poster production so easy when compared with using Tikz and LaTex.

Andrew
![in_rstudio](https://user-images.githubusercontent.com/2455814/33362143-e7049ca0-d4d2-11e7-8134-0034e0b3a63d.png)
![in_webbrowser](https://user-images.githubusercontent.com/2455814/33362147-ed37b90e-d4d2-11e7-9a8b-e0d2af7eee30.png)
[Untitled.Rmd.txt](https://github.com/bbucior/drposter/files/1512805/Untitled.Rmd.txt)

**Comment by bbucior** [comment]
Were you able to figure out the issue?  I recall encountering this problem during development but can't remember the specific cause off the top of my head: perhaps there needs to be an empty line between the `## Introduction` line and your content?  If that doesn't work, we could try a few other things.

**Comment by ar0berts** [comment]
Dear Ben,
I tried two lines, a backslash on the next line and various other formats but no success. I used the same format as in the .Rmd for your example poster but no success. I will try running the whole of you .Rmd example and report back.
Regards. 
Andrew

**Comment by ar0berts** [comment]
i've not managed to successfully reproduce your demo poster even after getting the american-chemical-society.csl in the right place and commenting out the external resources (`![](Resources/Rlogo.svg)` and `![QR code](Resources/qr_code.png)` ). It just produces a blank RStudio viewer and a text only web page in a web browser. 

I'm looking forward to your next version in the new year :-)

**Comment by bbucior** [comment]
Hi Andrew, I just uploaded many changes to the project, which should now include all of the relevant resources in the examples folder.  The RStudio preview is still incorrect (due to incompatibilities with newer CSS features), but it should work in a recent Chrome or Firefox.

I'll close this issue for now, but please feel free to reopen or submit a new one if you run into any problems.
