### ISSUE TITLE
Not working on Rstudio server

### ISSUE THREAD

**Issue by cmtso** [bbucior/drposter#13]
Hello, I am trying out the package on Rstudio server, which obviously can only use the Rstudio Viewer pane or pop it up to a new browser window or tab. Anyway to bypass the Chrome requirement and send output to the viewer pane? Or just save as pdf?

This is the error I get:

Error in find_chrome() : 
  Cannot find chromium-browser, chromium, or google-chrome
Calls: <Anonymous> ... <Anonymous> -> overlay -> chrome_pdf -> find_chrome
Execution halted

**Comment by bbucior** [comment]
Thanks for reporting this issue.

As a workaround, you should be able to bypass the Chrome requirement by using the `export_pdf: false` option in the yaml header, which should send the html output to the viewer pane. Please let me know if that avoids the error for your use case. Maybe over the next couple weekends, I could try adding a function to detect Rstudio server and send a javascript print command and user agent check+warning.

IIRC, before the Chrome PDF export feature, my workflow on RStudio Desktop was to compile the rmarkdown in the RStudio editor, refresh an open Chrome tab with the poster html, and print > Save as PDF. I tried getting the poster to work cross-browser, but couldn't get the auto-paper size or css grid styles to work.

**Comment by cmtso** [comment]
Many thanks. `export_pdf: false` solves the problem.
