### ISSUE TITLE
drposter.css not found when creating poster in RStudio as a template under the “New R Markdown” wizard

### ISSUE THREAD

**Issue by ElineVG** [bbucior/drposter#15]
Thank you so much for this wonderful package, which I have used for plenty of posters already! 
I wanted to explore using the newest version of the package directly from RStudio (by selecting the drposter template from the New R Markdown wizard). By default I get an html and pdf without formatting, however, with the html indicating the error: "drposter.css:1     Failed to load resource: net::ERR_FILE_NOT_FOUND".

This error only occurs when export_pdf is set to true (if export_pdf is set to false, everything works as expected and I get a html with layout). 
When adding a drposter_files directory underlying the existing drposter_files directory, and copying all files to this child directory too, the error when export_pdf is set to true was solved. 

I think there is probably a quick fix for this issue, just wanted to report that this is happening.

**Comment by bbucior** [comment]
Thanks for the feedback and digging into it to find the export_pdf differences!

Switching pandoc versions may be another workaround (until one of us finds the true fix). It appears that newer versions of rmarkdown are cleverly using the version of pandoc built into quarto. Switching back to the system install of pandoc also resolves the formatting issues on my laptop, i.e., via setting `Sys.setenv(RSTUDIO_PANDOC="/usr/bin/pandoc")` in my workspace before rendering.

**Comment by bbucior** [comment]
I ran out of time to debug today, but will try to revisit this week unless you beat me to it. Seems like the `export_pdf` flag leads to two different rmarkdown functions in drposter.R (`rmarkdown::output_format` vs. `rmarkdown::html_document`), so maybe there are different pandoc args being invoked.

**Comment by ElineVG** [comment]
Thanks for looking into it!
