### ISSUE TITLE
Paragraph wider than column

### ISSUE THREAD

**Issue by dhicks** [bbucior/drposter#8]
I'm just starting to play around with this package, and I've having trouble getting paragraph text to fit in its designated columns.  See the attached Rmd input and HTML output.  
[Archive.zip](https://github.com/bbucior/drposter/files/2457049/Archive.zip)

**Comment by dhicks** [comment]
It seems like this is related to the long URL in the second paragraph.  If that sentence is removed, the text is formatted correctly into two columns.

**Comment by bbucior** [comment]
Thanks for the example and debugging!  I'll send over a PR shortly to see if it meets your use case.
